name: Deploy on tag to main

on:
  push:
    tags:
      - 'v*'

jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify tag points to main
        run: |
          git fetch origin main --tags
          TAG_REF="${GITHUB_REF#refs/tags/}"
          TAG_SHA="$(git rev-list -n 1 "$TAG_REF")"
          git merge-base --is-ancestor "$TAG_SHA" origin/main || {
            echo "Tag $TAG_REF is not reachable from main; aborting deploy."; exit 1;
          }

      - name: Install dependencies (Python)
        run: |
          apt-get update
          apt-get install -y --no-install-recommends python3 python3-venv

      - name: Create venv and install dependencies
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate config.yaml for tests (dev, port 8000)
        run: |
          cat > config.yaml << 'YML'
          common:
            app_name: "Rezept Manager"
            version: "0.1.0"

          dev:
            host: "127.0.0.1"
            port: 8000
            debug: true
            reload: false
            root_path: ""
            database_url: "sqlite+aiosqlite:///./data/recipes.db"
            pdf_cache_dir: "./cache"

          prod:
            host: "0.0.0.0"
            port: 8081
            debug: false
            reload: false
            database_url: "sqlite+aiosqlite:////opt/rezepteapp/data/recipes.db"
            pdf_cache_dir: "/opt/rezepteapp/cache"
          YML

      - name: Initialize and seed database (dev)
        env:
          APP_ENV: dev
        run: |
          source .venv/bin/activate
          python3 tools/setup_db.py
          python3 tools/seed_data.py

      - name: Start app and run smoke tests
        env:
          APP_ENV: dev
        run: |
          source .venv/bin/activate
          .venv/bin/uvicorn main:app --host 127.0.0.1 --port 8000 --log-level warning & echo $! > uvicorn.pid
          sleep 5
          curl -f http://127.0.0.1:8000/ || { echo "Index failed"; exit 1; }
          curl -f http://127.0.0.1:8000/auth/login || { echo "Login page failed"; exit 1; }
          curl -f http://127.0.0.1:8000/api/help || { echo "Help API failed"; exit 1; }
          curl -f http://127.0.0.1:8000/recipe/1 || { echo "Recipe page failed"; exit 1; }
          kill $(cat uvicorn.pid) || true

      - name: Cleanup venv and data
        run: |
          rm -rf .venv data cache uvicorn.pid || true

  deploy:
    runs-on: ubuntu-latest
    needs: precheck
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
        run: |
          echo "DEBUG: Checking secrets..."
          echo "SSH_PRIVATE_KEY set: $([ -z "$SSH_PRIVATE_KEY" ] && echo "NO" || echo "YES")"
          echo "KNOWN_HOSTS set: $([ -z "$KNOWN_HOSTS" ] && echo "NO" || echo "YES")"
          mkdir -p ~/.ssh
          if [ -n "$SSH_PRIVATE_KEY" ]; then
            echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
            chmod 600 ~/.ssh/id_ed25519
            echo "SSH key written to ~/.ssh/id_ed25519"
            echo "SSH key fingerprint:"
            ssh-keygen -l -f ~/.ssh/id_ed25519
          else
            echo "ERROR: SSH_PRIVATE_KEY is empty!"
          fi
          if [ -n "$KNOWN_HOSTS" ]; then
            echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
            echo "Known hosts written to ~/.ssh/known_hosts"
            echo "Content:"
            cat ~/.ssh/known_hosts
          else
            echo "WARNING: KNOWN_HOSTS is empty!"
          fi

      - name: Deploy to server
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          PATH_DIR: ${{ secrets.DEPLOY_PATH }}
          SERVICE: ${{ secrets.DEPLOY_SERVICE }}
        run: |
          echo "DEBUG: Checking deploy secrets..."
          echo "DEPLOY_HOST set: $([ -z "$HOST" ] && echo "NO" || echo "YES")"
          echo "DEPLOY_USER set: $([ -z "$USER" ] && echo "NO" || echo "YES")"
          echo "DEPLOY_PATH set: $([ -z "$PATH_DIR" ] && echo "NO" || echo "YES")"
          echo "DEPLOY_SERVICE set: $([ -z "$SERVICE" ] && echo "NO" || echo "YES")"
          echo ""
          echo "SSH config:"
          ls -la ~/.ssh/
          echo ""
          TAG="${GITHUB_REF#refs/tags/}"
          echo "Deploying tag: $TAG"
          echo ""
          echo "SSH command to execute:"
          echo "ssh -i ~/.ssh/id_ed25519 -v -o StrictHostKeyChecking=no -o IdentitiesOnly=yes $USER@$HOST"
          echo ""
          echo "Remote commands:"
          echo "  cd $PATH_DIR"
          echo "  sudo systemctl stop $SERVICE"
          echo "  git fetch --tags origin"
          echo "  git fetch origin main"
          echo "  git checkout -f tags/$TAG"
          echo "  rm -rf cache"
          echo "  sudo systemctl start $SERVICE"
          echo ""
          echo "Executing SSH deploy..."
          ssh -i ~/.ssh/id_ed25519 -v -o StrictHostKeyChecking=no -o IdentitiesOnly=yes "$USER@$HOST" "
            set -e
            echo 'Connected to server, starting deployment...'
            cd \"$PATH_DIR\" && echo \"Changed to: $(pwd)\"
            echo 'Stopping service...'
            sudo systemctl stop \"$SERVICE\"
            echo 'Fetching tags...'
            git fetch --tags origin
            echo 'Fetching main branch...'
            git fetch origin main
            echo 'Checking out tag...'
            git checkout -f \"tags/$TAG\"
            echo 'Clearing cache...'
            rm -rf cache
            echo 'Starting service...'
            sudo systemctl start \"$SERVICE\"
            echo 'Deployment complete!'
          "
