name: Deploy on tag to main

on:
  push:
    tags:
      - 'v*'

jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify tag points to main
        run: |
          git fetch origin main --tags
          TAG_REF="${GITHUB_REF#refs/tags/}"
          TAG_SHA="$(git rev-list -n 1 "$TAG_REF")"
          git merge-base --is-ancestor "$TAG_SHA" origin/main || {
            echo "Tag $TAG_REF is not reachable from main; aborting deploy."; exit 1;
          }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Initialize and seed database (dev)
        env:
          APP_ENV: dev
        run: |
          python tools/setup_db.py
          python tools/seed_data.py

      - name: Start app and run smoke tests
        env:
          APP_ENV: dev
        run: |
          uvicorn main:app --host 127.0.0.1 --port 8000 --log-level warning & echo $! > uvicorn.pid
          sleep 3
          curl -f http://127.0.0.1:8000/ || { echo "Index failed"; exit 1; }
          curl -f http://127.0.0.1:8000/auth/login || { echo "Login page failed"; exit 1; }
          curl -f http://127.0.0.1:8000/api/help || { echo "Help API failed"; exit 1; }
          kill $(cat uvicorn.pid) || true

  deploy:
    runs-on: ubuntu-latest
    needs: precheck
    steps:
      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.DEPLOY_KNOWN_HOSTS }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          if [ -n "$KNOWN_HOSTS" ]; then
            echo "$KNOWN_HOSTS" > ~/.ssh/known_hosts
          fi

      - name: Deploy to server
        env:
          HOST: ${{ secrets.DEPLOY_HOST }}
          USER: ${{ secrets.DEPLOY_USER }}
          PATH_DIR: ${{ secrets.DEPLOY_PATH }}
          SERVICE: ${{ secrets.DEPLOY_SERVICE }}
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          ssh -o StrictHostKeyChecking=no "$USER@$HOST" "
            set -e
            cd \"$PATH_DIR\"
            sudo systemctl stop \"$SERVICE\"
            git fetch --tags origin
            git fetch origin main
            git checkout -f \"tags/$TAG\"
            rm -rf cache
            sudo systemctl start \"$SERVICE\"
          "
